/*
프로그래머스
과일로 만든 아이스크림 고르기
https://school.programmers.co.kr/learn/courses/30/lessons/133025
*/

SELECT 
    ICECREAM_INFO.FLAVOR
FROM
    ICECREAM_INFO
JOIN
    FIRST_HALF
    ON ICECREAM_INFO.FLAVOR=FIRST_HALF.FLAVOR
WHERE
    FIRST_HALF.TOTAL_ORDER > 3000
    AND ICECREAM_INFO.INGREDIENT_TYPE='fruit_based'
ORDER BY
    FIRST_HALF.TOTAL_ORDER desc;