WITH ECOLI_COUNT AS (
    SELECT COUNT(ID) AS COUNTS FROM ECOLI_DATA
),
ECOLI_TOP_PERCENT AS (
    SELECT
        ed.ID,
        (ROW_NUMBER() OVER (ORDER BY ed.SIZE_OF_COLONY DESC)) / ec.COUNTS AS TOP
    FROM
        ECOLI_DATA AS ed
    JOIN
        ECOLI_COUNT AS ec
)

SELECT
    ID,
    CASE
        WHEN TOP <= 0.25 THEN 'CRITICAL'
        WHEN TOP > 0.25 AND TOP <= 0.5 THEN 'HIGH'
        WHEN TOP > 0.50 AND TOP <= 0.75 THEN 'MEDIUM'
        WHEN TOP > 0.75 AND TOP <= 1 THEN 'LOW'
    END AS COLONY_NAME
FROM
    ECOLI_TOP_PERCENT
ORDER BY
    ID;
